apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-node
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: api-node
        resources:
          requests: { cpu: "50m", memory: "64Mi" }
          limits:   { cpu: "200m", memory: "256Mi" }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-python
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: api-python
        resources:
          requests: { cpu: "50m", memory: "64Mi" }
          limits:   { cpu: "200m", memory: "256Mi" }
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-node
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-node
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-python
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-python
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
